server:
  server_address: "0.0.0.0:8080"

postgresql:
  pg_host: "postgres"
  pg_port: "5432"
  pg_database: "db"
  pg_user: "user"
  pg_password: "password"

redis:
  redis_host: ""
  redis_port: ""
  redis_database: ""
  redis_user: ""
  redis_password: ""
