server:
  server_address: "0.0.0.0:8080"

postgresql:
  pg_host: "postgres"
  pg_port: "5432"
  pg_database: "db"
  pg_user: "user"
  pg_password: "password"

mongodb:
  mongo_database: "mongodb"
  mongo_host: "mongodb"
  mongo_port: "27017"
  mongo_user: "user"
  mongo_password: "password"